# Generated by Django 2.2.6 on 2021-07-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
